server:
  servlet:
    context-path: /api/bcos
  port: 8023

sdk:
  corePoolSize: 50
  maxPoolSize: 100
  queueCapacity: 100
  ip: 127.0.0.1
  channelPort: 20200
  certPath: conf  # cert path of relative or absolute
  useSMCrypto: false